name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }
      - name: Install dependencies
        run: npm ci
      - name: Type check (optional)
        run: npm run check || true
      - name: Build frontend
        run: npx vite build
      - name: Build backend
        run: npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist --log-level=warning || npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist --log-level=warning --minify=false